### ISSUE TITLE
Use installer on macOS 11.X

### ISSUE THREAD

**Issue by onekiloparsec** [reviewboard/pysvn-installer#1]
Hi. Thanks a lot for your very useful installer. It doesn't work on macOS 11.X BigSur as far as I can tell. 

I had to change some paths (it seems homebrew has changed some things – btw I am using an Apple Silicon M1 MacBookPro 13). Here are the paths inside the installer:

```
        # We want to include a few additional places to look for headers
        # and libraries. We'll start by seeing if Homebrew has some
        # information, and we'll then proceed to including the XCode versions.
        brew_svn_path = '/opt/homebrew/'
        apr_config_path = '/opt/homebrew/opt/apr/bin/apr-1-config'
        apu_config_path = '/opt/homebrew/opt/apr-util/bin/apu-1-config'
```

Sorry for not making a PR. I am not sure how you'd prefer to handle the different macOS cases.

**Comment by chipx86** [comment]
Sorry it took so long to address this. I haven't had a modern system to test on that had the `/opt/homebrew` paths until now.

This is now fixed. We query the paths from `brew`, which works regardless of the Intel homebrew paths (`/usr/local`) or the M1 homebrew paths (`/opt/homebrew`).
